### ISSUE TITLE
Coalesce about info

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-Hive/ACCESS-Hive#138]
Spawned from #70 

- [x] Merge "ACCESS-Hive" and "About" tabs. 
- [x] ~Maybe add a "Contributions" tab for the contribution guidelines.~
- [x] ~Add link to the main ACCESS-NRI website somewhere (https://github.com/ACCESS-Hive/ACCESS-Hive/issues/127, https://github.com/ACCESS-Hive/ACCESS-Hive/issues/43, https://github.com/ACCESS-Hive/ACCESS-Hive/issues/72 )~ moved to #145 
- [x] "About" page: refine the definition of "supported", "recommended" and "community" links (https://github.com/ACCESS-Hive/ACCESS-Hive/issues/114) A longer definition for each category.
- [x] Should ACCESS-Hive have an explanation about where the documentation supported by ACCESS-NRI will reside? (https://github.com/ACCESS-Hive/ACCESS-Hive/issues/127)
- [x] ~Acknowledgement / citation text (SAC)~
- [x] ~Acknowledgement of country? (https://github.com/ACCESS-Hive/ACCESS-Hive/issues/72) yes~
- [x] ~Code of conduct / ethics statement? (https://github.com/ACCESS-Hive/ACCESS-Hive/issues/72) natalia~
- [x] Add information on the level of support provided and where to go to ask for support (forum!!) (https://github.com/ACCESS-Hive/ACCESS-Hive/issues/72)

Moved code of conduct and acknowledgement of country to #146

Moved citation and contribution stuff to #147

I don't think we need an explanation about where ACCESS-NRI documentation resides, that is what ACCESS-Hive is for, to link to stuff.

**Comment by aidanheerdegen** [comment]
I've done the major rearrangement and some of the other items above. @ccarouge has thoroughly reviewed that and improved it further. We'll merge that PR now to make it easier for other contributions without having lots of merge conflict headaches.

I'll need input from Natalia on some of the other items, so this will likely go on the back-burner until after eResearch.

**Comment by aidanheerdegen** [comment]
Moved outstanding tasks to dedicated issues.
